source/main/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from webapp.views import *
from accounts.views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PostListView.as_view(), name='post_list'),
    path('user/all', UserListView.as_view(), name='user_list'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('accounts/login', login_view, name='login'),
    path('accounts/logout', logout_view, name='logout'),
    path('post/create', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('user/<int:pk>/update', UserUpdateView.as_view(), name='user_update'),
    path('user/<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('user/<int:pk>delete', UserDeleteView.as_view(), name='user_delete'),

]

source/accounts/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import User


class ProjectSearchForm(forms.Form):
    search_string = forms.CharField(max_length=200, required=False, label='Критерий поиска')


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='info', verbose_name='Пользователь')
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name='Имя')
    password = models.CharField(max_length=200, null=False, blank=False, verbose_name='Пароль')
    phone = models.CharField(max_length=20,verbose_name="Телефон")
    photo = models.ImageField(verbose_name='Фотография')
    email = models.EmailField(max_length=20, verbose_name="почта")
    friends = models.ForeignKey(User,  on_delete=models.PROTECT, verbose_name='Друзья')

    def __str__(self):
      #  return self.name
        return "%s. %s - %s" % (self.pk, self.user.userinfo_set, self.user.userinfo_set.get_full_name())

class Post(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name='Заголовок')
    text = models.TextField(max_length=200, null=False, blank=False, verbose_name='Содержимое')
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='author_post')
    date = models.DateField(verbose_name="Дата", auto_now_add=True)

    def __str__(self):
        return "%s by %s" % (self.title, self.author)
    

source/webapp/forms.py
from django import forms
from webapp.models import Post, User, UserInfo


class PostSearchForm(forms.Form):
    search_string = forms.CharField(max_length=200, required=False, label='Критерий поиска')


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'text', 'author']


class UserForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['photo', 'phone']

source/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is None:
            context = {
                'username': username,
                'password': password,
                'has_error': True
            }
            return render(request,'login.html', context=context)
        else:
            login(request, user=user)
            return redirect('post_list')
    return render(request,'login.html')

def logout_view(request):
    logout(request)
    return redirect('post_list')

source/webapp/views.py
from django.shortcuts import render, redirect, get_object_or_404#,reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, View, RedirectView,CreateView,UpdateView, DeleteView
from webapp.models import *
from django.urls import reverse_lazy
from webapp.forms import *
import datetime

class IndexView(TemplateView):
    template_name = 'index.html'
    context_object_name = 'post_list'


def get_context_date(self, **kwargs):
    context = super().get_context_date(**kwargs)
    return context

class PostListView(ListView):
    model = Post
    template_name = 'post_list.html'
    form_class = ProjectSearchForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        else:
            return super().dispatch(request, *args, **kwargs)


    def get_queryset(self):
         return Post.objects.all().order_by('date').reverse()

    def get_queryset(self):
        search_string = self.request.GET.get('search_string')
        if search_string:
            return self.model.objects.filter(post__icontains=search_string) | \
                   self.model.objects.filter(text__icontains=search_string)
        else:
            return self.model.objects.all()


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class PostCreateView(CreateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm
    success_url = reverse_lazy('post_list')

def post_create_view(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return render(request, 'post_create.html')
        else:
            return redirect('login')

    elif request.method == 'POST':
        title = request.POST.get('title')
        text = request.POST.get('text')
        author = request.user
        date = datetime.datetime.now()
        Post.objects.create(title=title, text=text, author=author,date=date)
        return redirect('post_list')



class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'post_update.html'
    success_url = reverse_lazy('post_list')

    def post_update_view(request):
        if request.method == 'GET':
            if request.user.is_authenticated:
                return render(request, 'post_update.html')
            else:
                return redirect('login')

        elif request.method == 'POST':
            title = request.POST.get('title')
            text = request.POST.get('text')
            author = request.user
            date = datetime.datetime.now()
            Post.objects.create(title=title, text=text, author=author, date=date)
            return redirect('post_list')


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')

def post_delete_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if not request.user.is_authenticated:
        return redirect('login')
    elif request.user == post.author:
        if request.method == 'GET':
            return render(request, 'post_delete.html', context={
                'post': post
            })
        elif request.method == 'POST':
            if request.POST.get('delete') == 'yes':
                post.delete()
            return redirect('../')
    else:
        return redirect('../post/'+str(pk))

class UserListView(ListView):
    model = UserInfo
    template_name = 'user_list.html'

class UserDetailView(DetailView):
    model = UserInfo
    template_name = 'user_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('date').reverse()
        return context

class UserUpdateView(UpdateView):
    model = UserInfo
    form_class = UserForm
    template_name = 'user_update.html'
    success_url = reverse_lazy('user_list')

class UserDeleteView(DeleteView):
        model = UserInfo
        fields = ['phone', 'image']
        form_class = UserForm
        template_name = 'user_delete.html'
        success_url = reverse_lazy('user_list')




# Create your views here.

source/accounts/templates/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <title>Вход</title>
</head>
<body>
<div class="container">
    <h1 class="text-center">Вход</h1>
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        {% if form.errors %}
            <p class="form-text text-danger text-center">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-row form-group">
            <label for="username" class="col-2 form-text">Имя пользователя:</label>
            <input type="text" class="form-control col-10" name="username" id="username"
                   value="{% if form.username.value %}{{ form.username.value }}{% endif %}">
        </div>
        <div class="form-row form-group">
            <label for="password" class="col-2 form-text">Пароль:</label>
            <input type="password" class="form-control col-10" name="password" id="password"
                   value="{% if form.password.value %}{{ form.password.value }}{% endif %}">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Войти</button>
        </div>
    </form>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
                <li class="nav-item navbar-text">Привет, {{ request.user.username }}!</li>
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">Выход</a>
                </li>
                <ul class="nav nav-tabs">
                      <li class="nav-item ">
                         <a class="nav-link" href="{% url 'post_list' %}" >Новости</a>
                      </li>
                      <li class="nav-item">
                       <a class="nav-link" href="{% url 'post_create' %}">Добавить пост</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_list' %}">Данные о пользователе</a>
                      </li>
                </ul>



            {% else %}
                <li class="nav-item">
                    <a href="{% url 'login' %}" class="nav-link">Вход</a>
                </li>


        </ul>
                <ul class="nav nav-tabs">
                      <li class="nav-item ">
                         <a class="nav-link" href="{% url 'post_list' %}" >Новости</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_list' %}">Данные о пользователе</a>
                      </li>
                </ul>

            {% endif %}
    </div>

        {% block menu %}{% endblock %}


</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends "base.html" %}

{% block title %}index{% endblock %}

{% block menu %}
{% endblock %}
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li>
                <a href="{% url 'index' %}" class="nav-link">На главную</a>

                <a href="{% url 'post_list' %}" class="nav-link">Новости</a>
                <a href="{% url 'post_create' %}">Добавить пост</a>

                <a href="#" class="nav-link">Пользователи</a>

                <a href="#" class="nav-link">Личный кабинет</a>

        </li>

        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

source/webapp/templates/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <title>Вход</title>
</head>
<body>
<div class="container">
    <h1 class="text-center">Вход</h1>
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        {% if form.errors %}
            <p class="form-text text-danger text-center">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-row form-group">
            <label for="username" class="col-2 form-text">Имя пользователя:</label>
            <input type="text" class="form-control col-10" name="username" id="username"
                   value="{% if form.username.value %}{{ form.username.value }}{% endif %}">
        </div>
        <div class="form-row form-group">
            <label for="password" class="col-2 form-text">Пароль:</label>
            <input type="password" class="form-control col-10" name="password" id="password"
                   value="{% if form.password.value %}{{ form.password.value }}{% endif %}">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Войти</button>
        </div>
    </form>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

source/webapp/templates/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

source/webapp/templates/post_delete.html
{% extends 'base.html' %}

{% block title %}Удалить пост{% endblock %}

{% block content %}
    <h1>Удалить пост</h1>
    <h5>Вы уверены, что хотите удалить пост {{ post.poct }}</h5>
    <form action="{% url 'post_delete' post.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
{% endblock %}

source/webapp/templates/post_detail.html
{% extends 'base.html' %}
{% block title %}Проект{% endblock %}

{% block content %}
    <div class="mt-3">
    <h1>{{ post.post }}</h1>
    <p>{{ post.text }}</p>
    <h5>Post <a href="{% url 'post_detail' post.pk %}">(+)</a></h5>
    {% for post in posts.list.all %}
        <p class="ml-5">{{ post.title }} ({{ post.author }})</p>
    {% endfor %}
    </div>

{% endblock %}

source/webapp/templates/post_list.html
{% extends "base.html" %}

{% block title %}View{% endblock %}

{% block menu %}
{% endblock %}
{% block content %}
    <div class="mt-3">
        <form action="{% url 'post_list' %}" method="GET">
            {% csrf_token %}
            <input type="поиск"> {{ form.search_string.label }} {{ form.search_string }}
            <button type="submit" class="btn btn-primary">Искать</button>
        </form>
    </div>
    <div class="mt-3">
        {% for post in post_list %}
            <h4><a href="{% url 'post_list'%}">{{ post.post }}</a></h4>
            <p>{{ post.title }}</p>
            <p><a href="{% url "post_detail" post.pk %}">Читать дальше...</a></p>
            <p>{{ post.author }}</p>
            <p>{{ post.date }}</p>
           <a href="{% url 'post_update' post.pk %}">Изменить</a>
           <a href="{% url 'post_delete' post.pk %}">Удалить</a>
            <hr>
        {% endfor %}
    </div>

{% endblock %}

source/webapp/templates/post_udate.html
{% extends 'base.html' %}

{% block title %}Редактировать пост{% endblock %}

{% block content %}
    <h1>Редактировать прост</h1>
    <form action="{% url 'post_update' form.post.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

source/webapp/templates/post_update.html
{% extends 'base.html' %}

{% block title %}Редактировать пост{% endblock %}

{% block content %}
    <h1>Редактировать пост</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

source/webapp/templates/user_delete.html
{% extends 'base.html' %}

{% block title %}Удалить пост{% endblock %}

{% block content %}
    <h1>Удалить пост</h1>
    <h5>Вы уверены, что хотите удалить пост {{ userinfo.user }}</h5>
    <form action="{% url 'user_delete' user.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
{% endblock %}

source/webapp/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}Редактировать пост{% endblock %}

{% block content %}

    <h3>Редактировать пользователя</h3>

    <p class="ml-5">{{ userinfo.name }} {{ userinfo.photo }} </p>
            {% for post in  userinfo.user.author_post.all %}
                <div>{{ post.title }}</div>
            {% endfor %}
{% endblock %}

source/webapp/templates/user_list.html
{% extends "base.html" %}

{% block title %}user info{% endblock %}

{% block menu %}
{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% block content %}
<div class="mt-3">
        <form action="{% url 'user_list' %}" method="GET">
            {% csrf_token %}
            <input type="поиск"> {{ form.search_string.label }} {{ form.search_string }}
            <button type="submit" class="btn btn-primary">Искать</button>
        </form>
    </div>
    <div class="mt-3">
        {% for user in userinfo_list %}
            <h4><a href="{% url 'user_list'%}">{{ user.user }}</a></h4>
            <p>Фото: {{ user.photo }}</p>
            <p>Имя: {{ user.name }}</p>
            <p>Почта: {{ user.email }}</p>
            <script>

        $(function () {
            let phone = $('.phone');
            phone.hide(1000);
            $('.btn').click(function () {
                phone.show(1000);
            });

        });
    </script>
    <p class="phone">Телефон: {{ user.phone }} </p><button class="btn">Паказать номер телефона</button>
                       </script>
            <p>Друзья: {{ user.friends }}</p>
            {% for user in userinfo_list %}
            {{ forloop.counter }}
            <p>Пост: {{ user.user.author_post.all }}</p>{% endfor %}
           <a href="{% url 'user_update' user.pk %}">Изменить</a>
           <a href="{% url 'user_delete' user.pk %}">Удалить</a>
            <hr>
        {% endfor %}
    </div>

{% endblock %}

source/webapp/templates/user_update.html
{% extends 'base.html' %}

{% block title %}Новый пост{% endblock %}

{% block content %}
    <h1>Редактирование пользователя</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}